# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import bank_pb2 as bank__pb2


class CurrencyServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getCurrency = channel.unary_stream(
        '/bank.CurrencyService/getCurrency',
        request_serializer=bank__pb2.CurrencyRequest.SerializeToString,
        response_deserializer=bank__pb2.CurrencyReply.FromString,
        )


class CurrencyServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def getCurrency(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_CurrencyServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getCurrency': grpc.unary_stream_rpc_method_handler(
          servicer.getCurrency,
          request_deserializer=bank__pb2.CurrencyRequest.FromString,
          response_serializer=bank__pb2.CurrencyReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'bank.CurrencyService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
